name: Unit and integration tests for library

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Install dependencies
      run: go mod tidy

    - name: Vet code
      run: go vet ./...

    - name: Run tests
      env:
        POSTGRES_CONNECTION_STRING: "postgres://postgres:password@localhost:5432/postgres?sslmode=disable"
      run: go test -v ./...

    - name: Run tests with race detection
      env:
        POSTGRES_CONNECTION_STRING: "postgres://postgres:password@localhost:5432/postgres?sslmode=disable"
      run: go test -race -v ./...

    - name: Check test coverage
      env:
        POSTGRES_CONNECTION_STRING: "postgres://postgres:password@localhost:5432/postgres?sslmode=disable"
      run: |
        go test -coverprofile=coverage.out ./...
        go tool cover -html=coverage.out -o coverage.html

    - name: Upload coverage reports
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coverage.html
