name: Unit tests

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: '1.20'

    - name: Install dependencies
      run: go mod tidy

    - name: Vet code
      run: go vet ./...

    - name: Run tests with coverage
      run: go test -v -coverprofile=coverage.txt ./...

    - name: Run tests with race detection
      run: go test -race -v ./...

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
